language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
env:
  - CI=true
branches:
  only:
    - master
install:
  - make
before_script:
  - make test
  - bash <(curl -s https://codecov.io/bash)
script:
  - make build
